### PR TITLE
Errorhandling

### PR DESCRIPTION
**Pull request by mortenn**
The current state of the core error catcher leaves me wanting.
This patch will let me handle core errors the way I want in my solutions, without changing the current default operation.

### CODE REVIEW

**Comment by mortenn** [comment]
I would like to be able to have an email dispatcher in addition to a html custom error response, but I am currently umming and arring about the kludginess of that.

**Comment by mortenn** [comment]
One way to solve my desire for email reports would be for the core error handler to invoke any dispatchers that are not instance of BufferDispatcher .. do you feel that would be too icky?

**Review by Kruithne — APPROVED** [review]
Seems fine. I don't have any initial complaints, other than the fact Travis seems to be throwing a hissy.

**Comment by mortenn** [comment]
From what I can tell from the logs, travis error has nothing to do with any tests, it's not even getting that far into the build that any tests are attempted..

**Pull request merged**
